### ISSUE TITLE
Temp-Sal plot only plot with x axis label on the bottom in section app

### ISSUE THREAD

**Issue by j-harbin** [dankelley/teaching_shiny#5]
In the app that shows profile in the oce section dataset (https://services.dal.ace-net.ca/shiny/dkelley/2020/section_view/), the Temp-Sal plot is the only plot with the x axis label on the bottom rather than the top. This is just an ascetic thing, however, here is a photo of what I mean because I know you *love* beautiful diagrams.

![Screen Shot 2020-08-31 at 7 53 40 AM](https://user-images.githubusercontent.com/58750538/91712916-1bdb5180-eb5f-11ea-8d10-c51352a2b03d.png)

**Comment by dankelley** [comment]
This also concerns me ... but I won't change it, because the oceanographic convention is to label profiles at the top, but a TS diagram at the bottom.  When I am making fancy diagrams, I sometimes place the TS below the S profile, with the T to the right of the S profile.  That way, the S values line up vertically and the p values line up horizontally.  I could do that as a special case,  but it would seem weird to do that (I think) only for this particular triplet.

It does look ugly though ...

I don't think I plan to change it...

OK...

dot dot dot ...

**Comment by j-harbin** [comment]
I also wouldn't go against the oceanographic convention. Although it may not be ideal, it's still very clear how to use the diagram, and that's the main thing.

I will close this issue.
