### ISSUE TITLE
PROPOSAL: Have changing colours for days in tide app

### ISSUE THREAD

**Issue by j-harbin** [dankelley/teaching_shiny#8]
In the app that shows that interesting time-series patterns can arise just a few tidal constituents (https://services.dal.ace-net.ca/shiny/dkelley/2020/tidal_constituents/), you could have alternating colours for days like you did for the viscous interval motion app.

It's not 100% necessary, as the tide is more or less indicative for the changes in day, but it was more or less food for thought.

**Comment by dankelley** [comment]
I'll think about this.  It might get messy.  Maybe I'll try it for views of under 1 week.  It would be nice, because you could see it coming in at different times of day (as people who spend time at cottages know). Thanks!

**Comment by dankelley** [comment]
Done in "master" commit 0bdcf9c49fac98a541ad0776c6f2992d0949884f.  I colourize if the time interval is under 35 days, because when the bands get too tight, it's hard to see very much.

Seem okay?

NOTE: it will take approximately 30 minutes for this change to propagate to the teaching website, but running the app within this repository will demonstrate whether I've fixed the problem.

**Comment by j-harbin** [comment]
+1 to this. I like the look of it. I am therefore closing this issue.
